// <auto-generated />
using GeekShoping.ProductAPI.Model.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GeekShoping.ProductAPI.Migrations
{
    [DbContext(typeof(MySQLContext))]
    partial class MySQLContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("GeekShoping.ProductAPI.Model.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CategoryName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CategoryName");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("Description");

                    b.Property<string>("ImageURL")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("ImageURL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("Price");

                    b.HasKey("Id");

                    b.ToTable("TB_Product");

                    b.HasData(
                        new
                        {
                            Id = 4L,
                            CategoryName = "Papelaria",
                            Description = "Caderno de anotações",
                            ImageURL = "https://example.com/caderno.jpg",
                            Name = "Caderno",
                            Price = 10.99m
                        },
                        new
                        {
                            Id = 5L,
                            CategoryName = "Papelaria",
                            Description = "Caneta esferográfica",
                            ImageURL = "https://example.com/caneta.jpg",
                            Name = "Caneta",
                            Price = 2.99m
                        },
                        new
                        {
                            Id = 6L,
                            CategoryName = "Acessórios",
                            Description = "Mochila para laptop",
                            ImageURL = "https://example.com/mochila.jpg",
                            Name = "Mochila",
                            Price = 49.99m
                        },
                        new
                        {
                            Id = 7L,
                            CategoryName = "Eletrônicos",
                            Description = "Fone de ouvido sem fio",
                            ImageURL = "https://example.com/fone.jpg",
                            Name = "Fone de Ouvido",
                            Price = 29.99m
                        },
                        new
                        {
                            Id = 8L,
                            CategoryName = "Acessórios",
                            Description = "Garrafa térmica para bebidas quentes ou frias",
                            ImageURL = "https://example.com/garrafa.jpg",
                            Name = "Garrafa Térmica",
                            Price = 19.99m
                        },
                        new
                        {
                            Id = 9L,
                            CategoryName = "Acessórios",
                            Description = "Relógio de pulso com design moderno",
                            ImageURL = "https://example.com/relogio.jpg",
                            Name = "Relógio de Pulso",
                            Price = 99.99m
                        },
                        new
                        {
                            Id = 10L,
                            CategoryName = "Roupas",
                            Description = "Camiseta de algodão confortável",
                            ImageURL = "https://example.com/camiseta.jpg",
                            Name = "Camiseta",
                            Price = 14.99m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
